# Generated by Django 4.1.1 on 2022-09-27 06:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="SlideShow",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("updated", models.DateTimeField(auto_now=True)),
                ("title", models.CharField(max_length=512, unique=True)),
                ("subject", models.CharField(max_length=100)),
                ("abstract", models.TextField(blank=True)),
                ("content_in_md", models.TextField(blank=True)),
                ("slug", models.SlugField()),
                ("length_in_minutes", models.IntegerField()),
                (
                    "author",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "slideshow",
                "verbose_name_plural": "slideshows",
            },
        ),
        migrations.CreateModel(
            name="Event",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("event_name", models.CharField(max_length=120)),
                ("venue", models.CharField(max_length=200)),
                ("event_start_date", models.DateField()),
                ("event_end_date", models.DateField()),
                ("presentation_date", models.DateField()),
                ("website", models.URLField(blank=True)),
                ("contact_email", models.EmailField(blank=True, max_length=254)),
                ("slug", models.SlugField(default="fakeevent")),
                (
                    "slideshow",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="slideshow.slideshow",
                    ),
                ),
            ],
            options={
                "verbose_name": "event",
                "verbose_name_plural": "events",
            },
        ),
    ]
