# Generated by Django 4.1.1 on 2022-09-29 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("slideshow", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="slideshow",
            name="slide_file",
            field=models.FilePathField(
                default="01_test_presentation.html",
                path="C:\\py\\dj\\django1\\apps\\slideshow\\templates\\slides",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="event",
            name="slug",
            field=models.SlugField(blank=True, default="fakeevent"),
        ),
    ]
