# Generated by Django 4.1.1 on 2022-10-04 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("slideshow", "0002_slideshow_slide_file_alter_event_slug"),
    ]

    operations = [
        migrations.RenameField(
            model_name="event",
            old_name="event_end_date",
            new_name="end_date",
        ),
        migrations.RenameField(
            model_name="event",
            old_name="event_name",
            new_name="name",
        ),
        migrations.RenameField(
            model_name="event",
            old_name="event_start_date",
            new_name="start_date",
        ),
        migrations.AlterField(
            model_name="slideshow",
            name="slide_file",
            field=models.FilePathField(
                path="C:\\py\\dj\\django1\\django1\\apps\\slideshow\\templates\\slideshow\\slides"
            ),
        ),
    ]
