# Generated by Django 4.1.1 on 2022-10-04 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("slideshow", "0003_rename_event_end_date_event_end_date_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="event",
            name="slug",
            field=models.SlugField(blank=True, default=""),
        ),
        migrations.AlterField(
            model_name="slideshow",
            name="slug",
            field=models.SlugField(blank=True, default=""),
        ),
    ]
