# Generated by Django 4.1.1 on 2022-10-04 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("slideshow", "0004_alter_event_slug_alter_slideshow_slug"),
    ]

    operations = [
        migrations.AddField(
            model_name="slideshow",
            name="slide_file_upload",
            field=models.FileField(
                blank=True,
                null=True,
                upload_to="C:\\py\\dj\\django1\\django1\\apps\\slideshow\\media",
            ),
        ),
        migrations.AlterField(
            model_name="slideshow",
            name="slide_file",
            field=models.FilePathField(
                path="C:\\py\\dj\\django1\\django1\\apps\\slideshow\\media"
            ),
        ),
    ]
