# Generated by Django 4.1.1 on 2022-10-06 04:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("slideshow", "0006_remove_slideshow_slide_file_upload_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="slideshow",
            name="content_in_md",
        ),
        migrations.RemoveField(
            model_name="slideshow",
            name="subject",
        ),
    ]
