# Generated by Django 4.1.1 on 2022-10-14 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("slideshow", "0007_remove_slideshow_content_in_md_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="slideshow",
            name="featured",
            field=models.BooleanField(default=False, null=True),
        ),
    ]
