# Generated by Django 4.1.1 on 2022-10-14 17:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("slideshow", "0009_alter_slideshow_featured"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="slideshow",
            name="featured",
        ),
    ]
