# Generated by Django 4.1.1 on 2022-10-14 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("slideshow", "0010_remove_slideshow_featured"),
    ]

    operations = [
        migrations.AddField(
            model_name="slideshow",
            name="featured",
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
