# Generated by Django 4.1.1 on 2022-10-14 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("slideshow", "0011_slideshow_featured"),
    ]

    operations = [
        migrations.AlterField(
            model_name="slideshow",
            name="featured",
            field=models.BooleanField(default=False),
        ),
    ]
