# Generated by Django 4.1.1 on 2022-10-16 02:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("slideshow", "0012_alter_slideshow_featured"),
    ]

    operations = [
        migrations.AddField(
            model_name="event",
            name="city",
            field=models.CharField(default="San Diego", max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="event",
            name="country",
            field=models.CharField(default="USA", max_length=120),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="event",
            name="state",
            field=models.CharField(blank=True, max_length=80),
        ),
    ]
